version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: indian_sm_dw_api
    container_name: indian-sm-api
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/db-test || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - api-net

networks:
  api-net:
    driver: bridge
